import type { Event } from './types';

// Data adapted from the Bolt project context provided by the user
export const eventsData: Event[] = [
  {
    id: '1',
    name: 'Espresso Innovation Summit',
    city: 'New York',
    country: 'USA',
    date: '2024-03-15',
    type: 'past',
    description:
      'A groundbreaking summit exploring the future of coffee technology and sustainable practices. Industry leaders gathered to discuss innovations in brewing techniques, sustainable sourcing, and the digital transformation of coffee culture.',
    attendees: 450,
    website: 'https://espresso.com/events/innovation-summit-2024',
    socialMedia: {
      twitter: '@EspressoSummit',
      instagram: '@espresso_innovation',
      linkedin: 'espresso-innovation-summit',
    },
    highlights: [
      'Keynote by James Hoffmann',
      'Sustainable sourcing workshop',
      'AI-powered brewing demos',
      'Networking with 50+ roasters',
    ],
    speakers: ['James Hoffmann', 'Sarah Chen', 'Marco Rodriguez', 'Dr. Elena Vasquez'],
    venue: 'Javits Center, Manhattan',
    images: ['https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg'],
    latitude: 40.7128,
    longitude: -74.0060,
    coordinates: { x: 22, y: 35 },
  },
  {
    id: '2',
    name: 'European Coffee Masters',
    city: 'Paris',
    country: 'France',
    date: '2024-05-22',
    type: 'past',
    description:
      'Elite baristas competed in our most prestigious European championship. A celebration of craftsmanship, precision, and the artistry that defines exceptional espresso.',
    attendees: 320,
    website: 'https://espresso.com/events/european-masters-2024',
    socialMedia: {
      twitter: '@EuropeanMasters',
      instagram: '@coffee_masters_eu',
    },
    highlights: [
      'Championship finals',
      'Latte art competition',
      'Origin tasting sessions',
      'Master class workshops',
    ],
    speakers: ['Pierre Dubois', 'Anna Kowalski', 'Giuseppe Romano'],
    venue: 'Palais des Congrès, Paris',
    images: ['https://images.pexels.com/photos/894695/pexels-photo-894695.jpeg'],
    latitude: 48.8566,
    longitude: 2.3522,
    coordinates: { x: 48, y: 30 },
  },
  {
    id: '3',
    name: 'Asian Espresso Expo',
    city: 'Tokyo',
    country: 'Japan',
    date: '2024-07-18',
    type: 'past',
    description:
      'Showcasing traditional and modern coffee culture across Asia. A fusion of ancient tea ceremony precision with contemporary espresso innovation.',
    attendees: 680,
    website: 'https://espresso.com/events/asian-expo-2024',
    socialMedia: {
      twitter: '@AsianEspressoExpo',
      instagram: '@espresso_asia',
    },
    highlights: [
      'Traditional vs Modern brewing',
      'Asian coffee origins tour',
      'Technology showcase',
      'Cultural exchange sessions',
    ],
    speakers: ['Hiroshi Tanaka', 'Li Wei Chen', 'Priya Sharma', 'Kim Min-jun'],
    venue: 'Tokyo International Forum',
    images: ['https://images.pexels.com/photos/1251175/pexels-photo-1251175.jpeg'],
    latitude: 35.6762,
    longitude: 139.6503,
    coordinates: { x: 82, y: 38 },
  },
  {
    id: '4',
    name: 'Latin American Bean Festival',
    city: 'São Paulo',
    country: 'Brazil',
    date: '2024-09-10',
    type: 'past',
    description:
      'Celebrating the rich coffee heritage of South America. From farm to cup, exploring the journey of exceptional beans and the passionate people behind them.',
    attendees: 520,
    website: 'https://espresso.com/events/latin-bean-festival-2024',
    socialMedia: {
      twitter: '@LatinBeanFest',
      instagram: '@latin_coffee_fest',
    },
    highlights: [
      'Farm-to-cup experiences',
      'Cupping competitions',
      'Sustainability workshops',
      'Cultural performances',
    ],
    speakers: ['Carlos Mendoza', 'Isabella Santos', 'Diego Ramirez'],
    venue: 'Centro de Convenções Frei Caneca',
    images: ['https://images.pexels.com/photos/1695052/pexels-photo-1695052.jpeg'],
    latitude: -23.5505,
    longitude: -46.6333,
    coordinates: { x: 32, y: 65 },
  },
  {
    id: '5',
    name: 'Nordic Coffee Revolution',
    city: 'Stockholm',
    country: 'Sweden',
    date: '2025-02-14',
    type: 'upcoming',
    description:
      'Exploring Scandinavian approaches to coffee perfection and sustainability. Discover the minimalist philosophy and environmental consciousness that defines Nordic coffee culture.',
    website: 'https://espresso.com/events/nordic-revolution-2025',
    socialMedia: {
      twitter: '@NordicCoffeeRev',
      instagram: '@nordic_coffee_revolution',
    },
    highlights: [
      'Sustainability keynotes',
      'Minimalist brewing techniques',
      'Environmental impact workshops',
      'Nordic roasting methods',
    ],
    speakers: ['Lars Andersen', 'Astrid Johansson', 'Erik Nilsson'],
    venue: 'Stockholm Waterfront Congress Centre',
    ticketPrice: 'Early bird: €299',
    latitude: 59.3293,
    longitude: 18.0686,
    coordinates: { x: 50, y: 22 },
  },
  {
    id: '6',
    name: 'Australian Roasting Championship',
    city: 'Melbourne',
    country: 'Australia',
    date: '2025-04-08',
    type: 'upcoming',
    description:
      "Down under's finest roasters showcase their craft and innovation. Experience the bold flavors and innovative techniques that make Australian coffee culture world-renowned.",
    website: 'https://espresso.com/events/australian-championship-2025',
    socialMedia: {
      twitter: '@AusRoastingChamp',
      instagram: '@aussie_roasting_champ',
    },
    highlights: [
      'Roasting competitions',
      'Flat white masterclasses',
      'Coffee cupping sessions',
      'Industry networking',
    ],
    speakers: ['Matt Perger', 'Sasa Sestic', 'Hugh Kelly'],
    venue: 'Melbourne Convention Centre',
    ticketPrice: 'From AUD $199',
    latitude: -37.8136,
    longitude: 144.9631,
    coordinates: { x: 85, y: 78 },
  },
  {
    id: '7',
    name: 'African Origin Experience',
    city: 'Nairobi',
    country: 'Kenya',
    date: '2025-06-20',
    type: 'upcoming',
    description:
      "Journey to the birthplace of coffee and discover untold stories. Connect with the origins of coffee culture and meet the farmers who cultivate the world's finest beans.",
    website: 'https://espresso.com/events/african-origins-2025',
    socialMedia: {
      twitter: '@AfricanOrigins',
      instagram: '@coffee_origins_africa',
    },
    highlights: ['Farm visits', 'Origin stories', 'Traditional ceremonies', 'Direct trade workshops'],
    speakers: ['Amara Kone', 'Joseph Mbugua', 'Fatima Al-Rashid'],
    venue: 'Kenyatta International Conference Centre',
    ticketPrice: 'USD $399 (includes farm tours)',
    latitude: -1.286389,
    longitude: 36.817223,
    coordinates: { x: 55, y: 60 },
  },
  {
    id: '8',
    name: 'Canadian Craft Coffee Con',
    city: 'Toronto',
    country: 'Canada',
    date: '2025-08-12',
    type: 'upcoming',
    description:
      'Northern hospitality meets exceptional coffee craftsmanship. Celebrate the growing Canadian coffee scene with artisanal roasters and innovative brewing methods.',
    website: 'https://espresso.com/events/canadian-craft-2025',
    socialMedia: {
      twitter: '@CanadianCraftCon',
      instagram: '@canadian_craft_coffee',
    },
    highlights: [
      'Craft roaster showcase',
      'Cold brew innovations',
      'Maple-infused creations',
      'Sustainability panel',
    ],
    speakers: ['Sarah Thompson', 'Michael Chen', 'Emma Rodriguez'],
    venue: 'Metro Toronto Convention Centre',
    ticketPrice: 'CAD $249',
    latitude: 43.65107,
    longitude: -79.347015,
    coordinates: { x: 20, y: 28 },
  },
  {
    id: '9',
    name: 'Middle East Coffee Forum',
    city: 'Dubai',
    country: 'UAE',
    date: '2025-10-05',
    type: 'upcoming',
    description:
      'A forum uniting roasters, café operators, and technologists across the Middle East with a focus on desert-friendly supply chains and water-wise brewing.',
    attendees: 700,
    website: 'https://espresso.com/events/me-coffee-forum-2025',
    socialMedia: { twitter: '@MEcoffeeforum' },
    highlights: ['Water-wise brewing', 'Desert logistics', 'Origin partnerships'],
    speakers: ['Layla Al Mansoori', 'Karim Haddad'],
    venue: 'Dubai World Trade Centre',
    images: ['https://images.pexels.com/photos/302901/pexels-photo-302901.jpeg'],
    latitude: 25.2048,
    longitude: 55.2708,
    coordinates: { x: 68, y: 48 },
  },
  {
    id: '10',
    name: 'Iberian Espresso Week',
    city: 'Lisbon',
    country: 'Portugal',
    date: '2025-11-12',
    type: 'upcoming',
    description:
      'A week-long celebration along the Atlantic: micro-roasters, seaside cuppings, and design-forward espresso bars.',
    attendees: 380,
    website: 'https://espresso.com/events/iberian-espresso-week-2025',
    highlights: ['Micro-roaster alley', 'Seaside cuppings', 'Bar design tour'],
    speakers: ['Inês Duarte', 'Javier Morales'],
    venue: 'LX Factory District',
    images: ['https://images.pexels.com/photos/230477/pexels-photo-230477.jpeg'],
    latitude: 38.7223,
    longitude: -9.1393,
    coordinates: { x: 38, y: 34 },
  },
  {
    id: '11',
    name: 'Caribbean Coffee Carnival',
    city: 'Kingston',
    country: 'Jamaica',
    date: '2025-12-03',
    type: 'upcoming',
    description:
      'Blue Mountain heritage, music, and festival espresso bars. A colorful close to the calendar year.',
    attendees: 420,
    website: 'https://espresso.com/events/caribbean-carnival-2025',
    highlights: ['Blue Mountain tastings', 'Carnival bar takeover'],
    venue: 'National Arena',
    images: ['https://images.pexels.com/photos/302887/pexels-photo-302887.jpeg'],
    latitude: 17.9712,
    longitude: -76.7920,
    coordinates: { x: 23, y: 45 },
  },
  {
    id: '12',
    name: 'Central Europe Roaster Summit',
    city: 'Prague',
    country: 'Czechia',
    date: '2025-09-01',
    type: 'upcoming',
    description:
      'Roasting science deep-dives and collaborative profile sessions with European champions.',
    attendees: 260,
    website: 'https://espresso.com/events/ce-roaster-summit-2025',
    highlights: ['Profile labs', 'Sensory calibration'],
    speakers: ['Tomas Novak', 'Katarina Horvathova'],
    venue: 'Prague Congress Centre',
    images: ['https://images.pexels.com/photos/1695053/pexels-photo-1695053.jpeg'],
    latitude: 50.0755,
    longitude: 14.4378,
    coordinates: { x: 45, y: 29 },
  },
  {
    id: '13',
    name: 'Pacific Northwest Espresso Camp',
    city: 'Seattle',
    country: 'USA',
    date: '2025-07-16',
    type: 'upcoming',
    description:
      'Outdoorsy brew gear demos, sustainable roasting workshops, and night latte art jams.',
    attendees: 500,
    website: 'https://espresso.com/events/pnw-espresso-camp-2025',
    highlights: ['Camp brew-offs', 'Sustainable roasting'],
    venue: 'Seattle Center',
    images: ['https://images.pexels.com/photos/414645/pexels-photo-414645.jpeg'],
    latitude: 47.6062,
    longitude: -122.3321,
    coordinates: { x: 14, y: 25 },
  },
  {
    id: '14',
    name: 'South Asia Café Congress',
    city: 'Bengaluru',
    country: 'India',
    date: '2025-03-22',
    type: 'upcoming',
    description:
      'Café operations, franchising playbooks, and robusta renaissance across South Asia.',
    attendees: 610,
    website: 'https://espresso.com/events/sa-cafe-congress-2025',
    highlights: ['Franchise clinics', 'Robusta renaissance'],
    speakers: ['Ravi Menon', 'Anjali Kapoor'],
    venue: 'BIEC',
    images: ['https://images.pexels.com/photos/681377/pexels-photo-681377.jpeg'],
    latitude: 12.9716,
    longitude: 77.5946,
    coordinates: { x: 72, y: 46 },
  },
];

